package cn.hd.cf.dao;

import cn.hd.cf.model.Initdata;
import cn.hd.cf.model.InitdataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InitdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    int countByExample(InitdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    int deleteByExample(InitdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    int insert(Initdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    int insertSelective(Initdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    List<Initdata> selectByExampleWithBLOBs(InitdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    List<Initdata> selectByExample(InitdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    Initdata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    int updateByExampleSelective(@Param("record") Initdata record, @Param("example") InitdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Initdata record, @Param("example") InitdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    int updateByExample(@Param("record") Initdata record, @Param("example") InitdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    int updateByPrimaryKeySelective(Initdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Initdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table initdata
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    int updateByPrimaryKey(Initdata record);
}