package cn.hd.cf.dao;

import cn.hd.cf.model.Player;
import cn.hd.cf.model.PlayerExample;
import cn.hd.cf.model.PlayerWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int countByExample(PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int deleteByExample(PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int deleteByPrimaryKey(Integer playerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int insert(PlayerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int insertSelective(PlayerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    List<PlayerWithBLOBs> selectByExampleWithBLOBs(PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    List<Player> selectByExample(PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    PlayerWithBLOBs selectByPrimaryKey(Integer playerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") PlayerWithBLOBs record, @Param("example") PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") PlayerWithBLOBs record, @Param("example") PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int updateByExample(@Param("record") Player record, @Param("example") PlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int updateByPrimaryKeySelective(PlayerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(PlayerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int updateByPrimaryKey(Player record);
}