package cn.hd.cf.dao;

import cn.hd.cf.model.Quest;
import cn.hd.cf.model.QuestExample;
import cn.hd.cf.model.QuestWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int countByExample(QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int deleteByExample(QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int insert(QuestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int insertSelective(QuestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    List<QuestWithBLOBs> selectByExampleWithBLOBs(QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    List<Quest> selectByExample(QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    QuestWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByExampleSelective(@Param("record") QuestWithBLOBs record, @Param("example") QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") QuestWithBLOBs record, @Param("example") QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByExample(@Param("record") Quest record, @Param("example") QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByPrimaryKeySelective(QuestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(QuestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByPrimaryKey(Quest record);
}