package cn.hd.cf.dao;

import cn.hd.cf.model.Quest;
import cn.hd.cf.model.QuestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int countByExample(QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int deleteByExample(QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int insert(Quest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int insertSelective(Quest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    List<Quest> selectByExample(QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    Quest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") Quest record, @Param("example") QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int updateByExample(@Param("record") Quest record, @Param("example") QuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int updateByPrimaryKeySelective(Quest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    int updateByPrimaryKey(Quest record);
}