package cn.hd.cf.dao;

import cn.hd.cf.model.Quotedata;
import cn.hd.cf.model.QuotedataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuotedataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    int countByExample(QuotedataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    int deleteByExample(QuotedataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    int insert(Quotedata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    int insertSelective(Quotedata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    List<Quotedata> selectByExampleWithBLOBs(QuotedataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    List<Quotedata> selectByExample(QuotedataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    Quotedata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    int updateByExampleSelective(@Param("record") Quotedata record, @Param("example") QuotedataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Quotedata record, @Param("example") QuotedataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    int updateByExample(@Param("record") Quotedata record, @Param("example") QuotedataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    int updateByPrimaryKeySelective(Quotedata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Quotedata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quotedata
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    int updateByPrimaryKey(Quotedata record);
}