package cn.hd.cf.dao;

import cn.hd.cf.model.Quote;
import cn.hd.cf.model.QuoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbggenerated Wed Jan 28 21:58:01 CST 2015
     */
    int countByExample(QuoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbggenerated Wed Jan 28 21:58:01 CST 2015
     */
    int deleteByExample(QuoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbggenerated Wed Jan 28 21:58:01 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbggenerated Wed Jan 28 21:58:01 CST 2015
     */
    int insert(Quote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbggenerated Wed Jan 28 21:58:01 CST 2015
     */
    int insertSelective(Quote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbggenerated Wed Jan 28 21:58:01 CST 2015
     */
    List<Quote> selectByExample(QuoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbggenerated Wed Jan 28 21:58:01 CST 2015
     */
    Quote selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbggenerated Wed Jan 28 21:58:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") Quote record, @Param("example") QuoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbggenerated Wed Jan 28 21:58:01 CST 2015
     */
    int updateByExample(@Param("record") Quote record, @Param("example") QuoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbggenerated Wed Jan 28 21:58:01 CST 2015
     */
    int updateByPrimaryKeySelective(Quote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbggenerated Wed Jan 28 21:58:01 CST 2015
     */
    int updateByPrimaryKey(Quote record);
}