package cn.hd.cf.dao;

import cn.hd.cf.model.Savingdata;
import cn.hd.cf.model.SavingdataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SavingdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    int countByExample(SavingdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    int deleteByExample(SavingdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    int deleteByPrimaryKey(Integer savingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    int insert(Savingdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    int insertSelective(Savingdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    List<Savingdata> selectByExampleWithBLOBs(SavingdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    List<Savingdata> selectByExample(SavingdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    Savingdata selectByPrimaryKey(Integer savingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    int updateByExampleSelective(@Param("record") Savingdata record, @Param("example") SavingdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Savingdata record, @Param("example") SavingdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    int updateByExample(@Param("record") Savingdata record, @Param("example") SavingdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    int updateByPrimaryKeySelective(Savingdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Savingdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savingdata
     *
     * @mbggenerated Sat Dec 20 12:15:59 CST 2014
     */
    int updateByPrimaryKey(Savingdata record);
}