package cn.hd.cf.dao;

import cn.hd.cf.model.Signindata;
import cn.hd.cf.model.SignindataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SignindataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int countByExample(SignindataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int deleteByExample(SignindataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int deleteByPrimaryKey(Integer signinid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int insert(Signindata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int insertSelective(Signindata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    List<Signindata> selectByExampleWithBLOBs(SignindataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    List<Signindata> selectByExample(SignindataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    Signindata selectByPrimaryKey(Integer signinid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByExampleSelective(@Param("record") Signindata record, @Param("example") SignindataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") Signindata record, @Param("example") SignindataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByExample(@Param("record") Signindata record, @Param("example") SignindataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByPrimaryKeySelective(Signindata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(Signindata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table signindata
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByPrimaryKey(Signindata record);
}