package cn.hd.cf.dao;

import cn.hd.cf.model.Title;
import cn.hd.cf.model.TitleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int countByExample(TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int deleteByExample(TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int insert(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int insertSelective(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    List<Title> selectByExample(TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    Title selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByExampleSelective(@Param("record") Title record, @Param("example") TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByExample(@Param("record") Title record, @Param("example") TitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByPrimaryKeySelective(Title record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table title
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    int updateByPrimaryKey(Title record);
}