package cn.hd.cf.model;

public class Event {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.id
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.desc
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.type
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.prize
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    private byte[] prize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.id
     *
     * @return the value of event.id
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.id
     *
     * @param id the value for event.id
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.desc
     *
     * @return the value of event.desc
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.desc
     *
     * @param desc the value for event.desc
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.type
     *
     * @return the value of event.type
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.type
     *
     * @param type the value for event.type
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.prize
     *
     * @return the value of event.prize
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public byte[] getPrize() {
        return prize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.prize
     *
     * @param prize the value for event.prize
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public void setPrize(byte[] prize) {
        this.prize = prize;
    }
}