package cn.hd.cf.model;

import java.util.Date;

public class Eventdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdata.eventid
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    private Integer eventid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdata.type
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdata.freq
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    private Integer freq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdata.createtime
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdata.version
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    private Float version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdata.status
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventdata.data
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdata.eventid
     *
     * @return the value of eventdata.eventid
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public Integer getEventid() {
        return eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdata.eventid
     *
     * @param eventid the value for eventdata.eventid
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdata.type
     *
     * @return the value of eventdata.type
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdata.type
     *
     * @param type the value for eventdata.type
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdata.freq
     *
     * @return the value of eventdata.freq
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public Integer getFreq() {
        return freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdata.freq
     *
     * @param freq the value for eventdata.freq
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public void setFreq(Integer freq) {
        this.freq = freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdata.createtime
     *
     * @return the value of eventdata.createtime
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdata.createtime
     *
     * @param createtime the value for eventdata.createtime
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdata.version
     *
     * @return the value of eventdata.version
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public Float getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdata.version
     *
     * @param version the value for eventdata.version
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public void setVersion(Float version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdata.status
     *
     * @return the value of eventdata.status
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdata.status
     *
     * @param status the value for eventdata.status
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventdata.data
     *
     * @return the value of eventdata.data
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventdata.data
     *
     * @param data the value for eventdata.data
     *
     * @mbggenerated Wed Dec 10 17:59:51 CST 2014
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}