package cn.hd.cf.model;

import java.util.Date;

public class Initdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column initdata.id
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column initdata.type
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column initdata.status
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column initdata.createtime
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column initdata.version
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    private Float version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column initdata.data
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column initdata.id
     *
     * @return the value of initdata.id
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column initdata.id
     *
     * @param id the value for initdata.id
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column initdata.type
     *
     * @return the value of initdata.type
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column initdata.type
     *
     * @param type the value for initdata.type
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column initdata.status
     *
     * @return the value of initdata.status
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column initdata.status
     *
     * @param status the value for initdata.status
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column initdata.createtime
     *
     * @return the value of initdata.createtime
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column initdata.createtime
     *
     * @param createtime the value for initdata.createtime
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column initdata.version
     *
     * @return the value of initdata.version
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public Float getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column initdata.version
     *
     * @param version the value for initdata.version
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public void setVersion(Float version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column initdata.data
     *
     * @return the value of initdata.data
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column initdata.data
     *
     * @param data the value for initdata.data
     *
     * @mbggenerated Sat Dec 20 11:12:43 CST 2014
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}