package cn.hd.cf.model;

import java.util.Date;

import cn.hd.base.Bean;

public class Insure extends Bean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.id
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.playerid
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private Integer playerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.itemid
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.name
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.descs
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.type
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.amount
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.price
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.qty
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private Integer qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.profit
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private Float profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.period
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.createtime
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insure.updatetime
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.id
     *
     * @return the value of insure.id
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.id
     *
     * @param id the value for insure.id
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.playerid
     *
     * @return the value of insure.playerid
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public Integer getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.playerid
     *
     * @param playerid the value for insure.playerid
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.itemid
     *
     * @return the value of insure.itemid
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.itemid
     *
     * @param itemid the value for insure.itemid
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.name
     *
     * @return the value of insure.name
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.name
     *
     * @param name the value for insure.name
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.descs
     *
     * @return the value of insure.descs
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.descs
     *
     * @param descs the value for insure.descs
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.type
     *
     * @return the value of insure.type
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.type
     *
     * @param type the value for insure.type
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.amount
     *
     * @return the value of insure.amount
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.amount
     *
     * @param amount the value for insure.amount
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.price
     *
     * @return the value of insure.price
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.price
     *
     * @param price the value for insure.price
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.qty
     *
     * @return the value of insure.qty
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.qty
     *
     * @param qty the value for insure.qty
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.profit
     *
     * @return the value of insure.profit
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public Float getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.profit
     *
     * @param profit the value for insure.profit
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setProfit(Float profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.period
     *
     * @return the value of insure.period
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.period
     *
     * @param period the value for insure.period
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.createtime
     *
     * @return the value of insure.createtime
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.createtime
     *
     * @param createtime the value for insure.createtime
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insure.updatetime
     *
     * @return the value of insure.updatetime
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insure.updatetime
     *
     * @param updatetime the value for insure.updatetime
     *
     * @mbggenerated Sun Dec 28 16:47:02 KRAT 2014
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}