package cn.hd.cf.model;

import java.util.Date;

public class Player {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.playerid
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private Integer playerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.playername
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private String playername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.pwd
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.accountid
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.sex
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.money
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private Float money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.exp
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private Integer exp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.job
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private Byte job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.saving
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private String saving;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.insure
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private String insure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.finan
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private String finan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.stock
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private String stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.quest
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private String quest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.zan
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private Integer zan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.createtime
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.version
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.versions
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    private String versions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.playerid
     *
     * @return the value of player.playerid
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public Integer getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.playerid
     *
     * @param playerid the value for player.playerid
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.playername
     *
     * @return the value of player.playername
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public String getPlayername() {
        return playername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.playername
     *
     * @param playername the value for player.playername
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setPlayername(String playername) {
        this.playername = playername == null ? null : playername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.pwd
     *
     * @return the value of player.pwd
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.pwd
     *
     * @param pwd the value for player.pwd
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.accountid
     *
     * @return the value of player.accountid
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.accountid
     *
     * @param accountid the value for player.accountid
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.sex
     *
     * @return the value of player.sex
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.sex
     *
     * @param sex the value for player.sex
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.money
     *
     * @return the value of player.money
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.money
     *
     * @param money the value for player.money
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.exp
     *
     * @return the value of player.exp
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.exp
     *
     * @param exp the value for player.exp
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.job
     *
     * @return the value of player.job
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public Byte getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.job
     *
     * @param job the value for player.job
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setJob(Byte job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.saving
     *
     * @return the value of player.saving
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public String getSaving() {
        return saving;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.saving
     *
     * @param saving the value for player.saving
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setSaving(String saving) {
        this.saving = saving == null ? null : saving.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.insure
     *
     * @return the value of player.insure
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public String getInsure() {
        return insure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.insure
     *
     * @param insure the value for player.insure
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setInsure(String insure) {
        this.insure = insure == null ? null : insure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.finan
     *
     * @return the value of player.finan
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public String getFinan() {
        return finan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.finan
     *
     * @param finan the value for player.finan
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setFinan(String finan) {
        this.finan = finan == null ? null : finan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.stock
     *
     * @return the value of player.stock
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public String getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.stock
     *
     * @param stock the value for player.stock
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setStock(String stock) {
        this.stock = stock == null ? null : stock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.quest
     *
     * @return the value of player.quest
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public String getQuest() {
        return quest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.quest
     *
     * @param quest the value for player.quest
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setQuest(String quest) {
        this.quest = quest == null ? null : quest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.zan
     *
     * @return the value of player.zan
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public Integer getZan() {
        return zan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.zan
     *
     * @param zan the value for player.zan
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setZan(Integer zan) {
        this.zan = zan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.createtime
     *
     * @return the value of player.createtime
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.createtime
     *
     * @param createtime the value for player.createtime
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.version
     *
     * @return the value of player.version
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.version
     *
     * @param version the value for player.version
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.versions
     *
     * @return the value of player.versions
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public String getVersions() {
        return versions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.versions
     *
     * @param versions the value for player.versions
     *
     * @mbggenerated Thu Dec 25 11:03:51 CST 2014
     */
    public void setVersions(String versions) {
        this.versions = versions == null ? null : versions.trim();
    }
}