package cn.hd.cf.model;

public class PlayerWithBLOBs extends Player {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.savings
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    private byte[] savings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.base
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    private byte[] base;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.event
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    private byte[] event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.insure
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    private byte[] insure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.stock
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    private byte[] stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.title
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    private byte[] title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.quest
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    private byte[] quest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.feelings
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    private byte[] feelings;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.savings
     *
     * @return the value of player.savings
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public byte[] getSavings() {
        return savings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.savings
     *
     * @param savings the value for player.savings
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public void setSavings(byte[] savings) {
        this.savings = savings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.base
     *
     * @return the value of player.base
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public byte[] getBase() {
        return base;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.base
     *
     * @param base the value for player.base
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public void setBase(byte[] base) {
        this.base = base;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.event
     *
     * @return the value of player.event
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public byte[] getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.event
     *
     * @param event the value for player.event
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public void setEvent(byte[] event) {
        this.event = event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.insure
     *
     * @return the value of player.insure
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public byte[] getInsure() {
        return insure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.insure
     *
     * @param insure the value for player.insure
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public void setInsure(byte[] insure) {
        this.insure = insure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.stock
     *
     * @return the value of player.stock
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public byte[] getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.stock
     *
     * @param stock the value for player.stock
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public void setStock(byte[] stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.title
     *
     * @return the value of player.title
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public byte[] getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.title
     *
     * @param title the value for player.title
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public void setTitle(byte[] title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.quest
     *
     * @return the value of player.quest
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public byte[] getQuest() {
        return quest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.quest
     *
     * @param quest the value for player.quest
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public void setQuest(byte[] quest) {
        this.quest = quest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.feelings
     *
     * @return the value of player.feelings
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public byte[] getFeelings() {
        return feelings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.feelings
     *
     * @param feelings the value for player.feelings
     *
     * @mbggenerated Thu Nov 20 17:13:16 CST 2014
     */
    public void setFeelings(byte[] feelings) {
        this.feelings = feelings;
    }
}