package cn.hd.cf.model;

public class PlayerWithBLOBs extends Player {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.savings
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    private byte[] savings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.base
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    private byte[] base;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.event
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    private byte[] event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.title
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    private byte[] title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.feelings
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    private byte[] feelings;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.savings
     *
     * @return the value of player.savings
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    public byte[] getSavings() {
        return savings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.savings
     *
     * @param savings the value for player.savings
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    public void setSavings(byte[] savings) {
        this.savings = savings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.base
     *
     * @return the value of player.base
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    public byte[] getBase() {
        return base;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.base
     *
     * @param base the value for player.base
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    public void setBase(byte[] base) {
        this.base = base;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.event
     *
     * @return the value of player.event
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    public byte[] getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.event
     *
     * @param event the value for player.event
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    public void setEvent(byte[] event) {
        this.event = event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.title
     *
     * @return the value of player.title
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    public byte[] getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.title
     *
     * @param title the value for player.title
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    public void setTitle(byte[] title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.feelings
     *
     * @return the value of player.feelings
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    public byte[] getFeelings() {
        return feelings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.feelings
     *
     * @param feelings the value for player.feelings
     *
     * @mbggenerated Sat Dec 13 11:26:45 CST 2014
     */
    public void setFeelings(byte[] feelings) {
        this.feelings = feelings;
    }
}