package cn.hd.cf.model;

import java.util.Date;

public class Questdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questdata.questid
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    private Integer questid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questdata.type
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questdata.createtime
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questdata.status
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questdata.version
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    private Float version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questdata.data
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questdata.questid
     *
     * @return the value of questdata.questid
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public Integer getQuestid() {
        return questid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questdata.questid
     *
     * @param questid the value for questdata.questid
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public void setQuestid(Integer questid) {
        this.questid = questid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questdata.type
     *
     * @return the value of questdata.type
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questdata.type
     *
     * @param type the value for questdata.type
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questdata.createtime
     *
     * @return the value of questdata.createtime
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questdata.createtime
     *
     * @param createtime the value for questdata.createtime
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questdata.status
     *
     * @return the value of questdata.status
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questdata.status
     *
     * @param status the value for questdata.status
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questdata.version
     *
     * @return the value of questdata.version
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public Float getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questdata.version
     *
     * @param version the value for questdata.version
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public void setVersion(Float version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questdata.data
     *
     * @return the value of questdata.data
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questdata.data
     *
     * @param data the value for questdata.data
     *
     * @mbggenerated Mon Dec 08 17:48:02 CST 2014
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}