package cn.hd.cf.model;

public class QuestWithBLOBs extends Quest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.need
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    private byte[] need;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.cost
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    private byte[] cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.target
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    private byte[] target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.prize
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    private byte[] prize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.need
     *
     * @return the value of quest.need
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public byte[] getNeed() {
        return need;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.need
     *
     * @param need the value for quest.need
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public void setNeed(byte[] need) {
        this.need = need;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.cost
     *
     * @return the value of quest.cost
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public byte[] getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.cost
     *
     * @param cost the value for quest.cost
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public void setCost(byte[] cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.target
     *
     * @return the value of quest.target
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public byte[] getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.target
     *
     * @param target the value for quest.target
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public void setTarget(byte[] target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.prize
     *
     * @return the value of quest.prize
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public byte[] getPrize() {
        return prize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.prize
     *
     * @param prize the value for quest.prize
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public void setPrize(byte[] prize) {
        this.prize = prize;
    }
}