package cn.hd.cf.model;

import java.util.Date;

public class Quest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.id
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.playerid
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    private Integer playerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.tel
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.crdate
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    private Date crdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.id
     *
     * @return the value of quest.id
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.id
     *
     * @param id the value for quest.id
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.playerid
     *
     * @return the value of quest.playerid
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    public Integer getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.playerid
     *
     * @param playerid the value for quest.playerid
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.tel
     *
     * @return the value of quest.tel
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.tel
     *
     * @param tel the value for quest.tel
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.crdate
     *
     * @return the value of quest.crdate
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.crdate
     *
     * @param crdate the value for quest.crdate
     *
     * @mbggenerated Sat Sep 26 09:48:14 CST 2015
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }
}