package cn.hd.cf.model;

public class Quest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.id
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.type
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.name
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quest.desc
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.id
     *
     * @return the value of quest.id
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.id
     *
     * @param id the value for quest.id
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.type
     *
     * @return the value of quest.type
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.type
     *
     * @param type the value for quest.type
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.name
     *
     * @return the value of quest.name
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.name
     *
     * @param name the value for quest.name
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quest.desc
     *
     * @return the value of quest.desc
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quest.desc
     *
     * @param desc the value for quest.desc
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}