package cn.hd.cf.model;

public class Quote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote.id
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote.stockid
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    private Integer stockid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote.date
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote.upprice
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    private Float upprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote.price
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote.lowprice
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    private Float lowprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote.openprice
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    private Float openprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote.qty
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    private Integer qty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote.id
     *
     * @return the value of quote.id
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote.id
     *
     * @param id the value for quote.id
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote.stockid
     *
     * @return the value of quote.stockid
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public Integer getStockid() {
        return stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote.stockid
     *
     * @param stockid the value for quote.stockid
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public void setStockid(Integer stockid) {
        this.stockid = stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote.date
     *
     * @return the value of quote.date
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote.date
     *
     * @param date the value for quote.date
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote.upprice
     *
     * @return the value of quote.upprice
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public Float getUpprice() {
        return upprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote.upprice
     *
     * @param upprice the value for quote.upprice
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public void setUpprice(Float upprice) {
        this.upprice = upprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote.price
     *
     * @return the value of quote.price
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote.price
     *
     * @param price the value for quote.price
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote.lowprice
     *
     * @return the value of quote.lowprice
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public Float getLowprice() {
        return lowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote.lowprice
     *
     * @param lowprice the value for quote.lowprice
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public void setLowprice(Float lowprice) {
        this.lowprice = lowprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote.openprice
     *
     * @return the value of quote.openprice
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public Float getOpenprice() {
        return openprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote.openprice
     *
     * @param openprice the value for quote.openprice
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public void setOpenprice(Float openprice) {
        this.openprice = openprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote.qty
     *
     * @return the value of quote.qty
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote.qty
     *
     * @param qty the value for quote.qty
     *
     * @mbggenerated Sat Dec 20 15:16:50 CST 2014
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }
}