package cn.hd.cf.model;

import java.util.Date;

public class Quotedata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotedata.id
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotedata.stockid
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    private Integer stockid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotedata.name
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotedata.type
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotedata.status
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotedata.createtime
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotedata.version
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    private Float version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quotedata.data
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotedata.id
     *
     * @return the value of quotedata.id
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotedata.id
     *
     * @param id the value for quotedata.id
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotedata.stockid
     *
     * @return the value of quotedata.stockid
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public Integer getStockid() {
        return stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotedata.stockid
     *
     * @param stockid the value for quotedata.stockid
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public void setStockid(Integer stockid) {
        this.stockid = stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotedata.name
     *
     * @return the value of quotedata.name
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotedata.name
     *
     * @param name the value for quotedata.name
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotedata.type
     *
     * @return the value of quotedata.type
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotedata.type
     *
     * @param type the value for quotedata.type
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotedata.status
     *
     * @return the value of quotedata.status
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotedata.status
     *
     * @param status the value for quotedata.status
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotedata.createtime
     *
     * @return the value of quotedata.createtime
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotedata.createtime
     *
     * @param createtime the value for quotedata.createtime
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotedata.version
     *
     * @return the value of quotedata.version
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public Float getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotedata.version
     *
     * @param version the value for quotedata.version
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public void setVersion(Float version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quotedata.data
     *
     * @return the value of quotedata.data
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quotedata.data
     *
     * @param data the value for quotedata.data
     *
     * @mbggenerated Sat Dec 20 15:24:11 CST 2014
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}