package cn.hd.cf.model;

import java.util.Date;

public class Savingdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savingdata.savingid
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    private Integer savingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savingdata.type
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savingdata.createtime
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savingdata.status
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savingdata.version
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    private Float version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savingdata.data
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savingdata.savingid
     *
     * @return the value of savingdata.savingid
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public Integer getSavingid() {
        return savingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savingdata.savingid
     *
     * @param savingid the value for savingdata.savingid
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public void setSavingid(Integer savingid) {
        this.savingid = savingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savingdata.type
     *
     * @return the value of savingdata.type
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savingdata.type
     *
     * @param type the value for savingdata.type
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savingdata.createtime
     *
     * @return the value of savingdata.createtime
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savingdata.createtime
     *
     * @param createtime the value for savingdata.createtime
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savingdata.status
     *
     * @return the value of savingdata.status
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savingdata.status
     *
     * @param status the value for savingdata.status
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savingdata.version
     *
     * @return the value of savingdata.version
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public Float getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savingdata.version
     *
     * @param version the value for savingdata.version
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public void setVersion(Float version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savingdata.data
     *
     * @return the value of savingdata.data
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savingdata.data
     *
     * @param data the value for savingdata.data
     *
     * @mbggenerated Tue Dec 16 17:39:00 CST 2014
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}