package cn.hd.cf.model;

public class Signin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.id
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.name
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.day
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.desc
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.type
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column signin.value
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.id
     *
     * @return the value of signin.id
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.id
     *
     * @param id the value for signin.id
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.name
     *
     * @return the value of signin.name
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.name
     *
     * @param name the value for signin.name
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.day
     *
     * @return the value of signin.day
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.day
     *
     * @param day the value for signin.day
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.desc
     *
     * @return the value of signin.desc
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.desc
     *
     * @param desc the value for signin.desc
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.type
     *
     * @return the value of signin.type
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.type
     *
     * @param type the value for signin.type
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column signin.value
     *
     * @return the value of signin.value
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column signin.value
     *
     * @param value the value for signin.value
     *
     * @mbggenerated Mon Dec 01 11:22:28 CST 2014
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}