package cn.hd.cf.model;

import java.util.Date;

public class Stockdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.stockid
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Integer stockid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.type
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.createtime
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.status
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.version
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Float version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.data
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.stockid
     *
     * @return the value of stockdata.stockid
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Integer getStockid() {
        return stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.stockid
     *
     * @param stockid the value for stockdata.stockid
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setStockid(Integer stockid) {
        this.stockid = stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.type
     *
     * @return the value of stockdata.type
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.type
     *
     * @param type the value for stockdata.type
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.createtime
     *
     * @return the value of stockdata.createtime
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.createtime
     *
     * @param createtime the value for stockdata.createtime
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.status
     *
     * @return the value of stockdata.status
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.status
     *
     * @param status the value for stockdata.status
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.version
     *
     * @return the value of stockdata.version
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Float getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.version
     *
     * @param version the value for stockdata.version
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setVersion(Float version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.data
     *
     * @return the value of stockdata.data
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.data
     *
     * @param data the value for stockdata.data
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}