package cn.hd.cf.model;

import java.util.Date;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.playerid
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private Integer playerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stockid
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private Integer stockid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.name
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.desc
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.amount
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.unit
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private Integer unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.qty
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private Integer qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.price
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.createtime
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.status
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.per
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private Integer per;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.quote
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    private byte[] quote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.playerid
     *
     * @return the value of stock.playerid
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public Integer getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.playerid
     *
     * @param playerid the value for stock.playerid
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stockid
     *
     * @return the value of stock.stockid
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public Integer getStockid() {
        return stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stockid
     *
     * @param stockid the value for stock.stockid
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setStockid(Integer stockid) {
        this.stockid = stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.name
     *
     * @return the value of stock.name
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.name
     *
     * @param name the value for stock.name
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.desc
     *
     * @return the value of stock.desc
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.desc
     *
     * @param desc the value for stock.desc
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.amount
     *
     * @return the value of stock.amount
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.amount
     *
     * @param amount the value for stock.amount
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.unit
     *
     * @return the value of stock.unit
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.unit
     *
     * @param unit the value for stock.unit
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.qty
     *
     * @return the value of stock.qty
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.qty
     *
     * @param qty the value for stock.qty
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.price
     *
     * @return the value of stock.price
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.price
     *
     * @param price the value for stock.price
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.createtime
     *
     * @return the value of stock.createtime
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.createtime
     *
     * @param createtime the value for stock.createtime
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.status
     *
     * @return the value of stock.status
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.status
     *
     * @param status the value for stock.status
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.per
     *
     * @return the value of stock.per
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public Integer getPer() {
        return per;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.per
     *
     * @param per the value for stock.per
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setPer(Integer per) {
        this.per = per;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.quote
     *
     * @return the value of stock.quote
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public byte[] getQuote() {
        return quote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.quote
     *
     * @param quote the value for stock.quote
     *
     * @mbggenerated Sat Dec 20 17:59:02 CST 2014
     */
    public void setQuote(byte[] quote) {
        this.quote = quote;
    }
}