package cn.hd.cf.model;

import java.util.Date;

public class Stockdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.id
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.name
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.per
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    private Byte per;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.descs
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.type
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.freq
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    private Integer freq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.jsonquotes
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    private String jsonquotes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.createtime
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.status
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.version
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    private Float version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockdata.quotes
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    private byte[] quotes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.id
     *
     * @return the value of stockdata.id
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.id
     *
     * @param id the value for stockdata.id
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.name
     *
     * @return the value of stockdata.name
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.name
     *
     * @param name the value for stockdata.name
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.per
     *
     * @return the value of stockdata.per
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public Byte getPer() {
        return per;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.per
     *
     * @param per the value for stockdata.per
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public void setPer(Byte per) {
        this.per = per;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.descs
     *
     * @return the value of stockdata.descs
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.descs
     *
     * @param descs the value for stockdata.descs
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.type
     *
     * @return the value of stockdata.type
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.type
     *
     * @param type the value for stockdata.type
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.freq
     *
     * @return the value of stockdata.freq
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public Integer getFreq() {
        return freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.freq
     *
     * @param freq the value for stockdata.freq
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public void setFreq(Integer freq) {
        this.freq = freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.jsonquotes
     *
     * @return the value of stockdata.jsonquotes
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public String getJsonquotes() {
        return jsonquotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.jsonquotes
     *
     * @param jsonquotes the value for stockdata.jsonquotes
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public void setJsonquotes(String jsonquotes) {
        this.jsonquotes = jsonquotes == null ? null : jsonquotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.createtime
     *
     * @return the value of stockdata.createtime
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.createtime
     *
     * @param createtime the value for stockdata.createtime
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.status
     *
     * @return the value of stockdata.status
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.status
     *
     * @param status the value for stockdata.status
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.version
     *
     * @return the value of stockdata.version
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public Float getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.version
     *
     * @param version the value for stockdata.version
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public void setVersion(Float version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockdata.quotes
     *
     * @return the value of stockdata.quotes
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public byte[] getQuotes() {
        return quotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockdata.quotes
     *
     * @param quotes the value for stockdata.quotes
     *
     * @mbggenerated Fri Dec 26 11:25:44 CST 2014
     */
    public void setQuotes(byte[] quotes) {
        this.quotes = quotes;
    }
}