package cn.hd.cf.model;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.name
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.desc
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.buyprice
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Float buyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.price
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.profit
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Float profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.holder
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Integer holder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.name
     *
     * @return the value of stock.name
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.name
     *
     * @param name the value for stock.name
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.desc
     *
     * @return the value of stock.desc
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.desc
     *
     * @param desc the value for stock.desc
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.buyprice
     *
     * @return the value of stock.buyprice
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Float getBuyprice() {
        return buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.buyprice
     *
     * @param buyprice the value for stock.buyprice
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setBuyprice(Float buyprice) {
        this.buyprice = buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.price
     *
     * @return the value of stock.price
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.price
     *
     * @param price the value for stock.price
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.profit
     *
     * @return the value of stock.profit
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Float getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.profit
     *
     * @param profit the value for stock.profit
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setProfit(Float profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.holder
     *
     * @return the value of stock.holder
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Integer getHolder() {
        return holder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.holder
     *
     * @param holder the value for stock.holder
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setHolder(Integer holder) {
        this.holder = holder;
    }
}