package cn.hd.cf.model;

import java.util.Date;

public class Titledata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titledata.titleid
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Integer titleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titledata.type
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titledata.createtime
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titledata.status
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titledata.version
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Float version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titledata.data
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titledata.titleid
     *
     * @return the value of titledata.titleid
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Integer getTitleid() {
        return titleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titledata.titleid
     *
     * @param titleid the value for titledata.titleid
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setTitleid(Integer titleid) {
        this.titleid = titleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titledata.type
     *
     * @return the value of titledata.type
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titledata.type
     *
     * @param type the value for titledata.type
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titledata.createtime
     *
     * @return the value of titledata.createtime
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titledata.createtime
     *
     * @param createtime the value for titledata.createtime
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titledata.status
     *
     * @return the value of titledata.status
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titledata.status
     *
     * @param status the value for titledata.status
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titledata.version
     *
     * @return the value of titledata.version
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Float getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titledata.version
     *
     * @param version the value for titledata.version
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setVersion(Float version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titledata.data
     *
     * @return the value of titledata.data
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titledata.data
     *
     * @param data the value for titledata.data
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}