package cn.hd.cf.model;

public class Title {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.id
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.name
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.desc
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.exp
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Integer exp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column title.level
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.id
     *
     * @return the value of title.id
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.id
     *
     * @param id the value for title.id
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.name
     *
     * @return the value of title.name
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.name
     *
     * @param name the value for title.name
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.desc
     *
     * @return the value of title.desc
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.desc
     *
     * @param desc the value for title.desc
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.exp
     *
     * @return the value of title.exp
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.exp
     *
     * @param exp the value for title.exp
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column title.level
     *
     * @return the value of title.level
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column title.level
     *
     * @param level the value for title.level
     *
     * @mbggenerated Sun Dec 07 15:41:57 CST 2014
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}