package cn.hd.cf.model;

import java.util.Date;

public class Toplist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toplist.id
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toplist.type
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toplist.playerid
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    private Integer playerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toplist.playername
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    private String playername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toplist.money
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    private Float money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toplist.score
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toplist.zan
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    private Integer zan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toplist.createtime
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toplist.id
     *
     * @return the value of toplist.id
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toplist.id
     *
     * @param id the value for toplist.id
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toplist.type
     *
     * @return the value of toplist.type
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toplist.type
     *
     * @param type the value for toplist.type
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toplist.playerid
     *
     * @return the value of toplist.playerid
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public Integer getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toplist.playerid
     *
     * @param playerid the value for toplist.playerid
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toplist.playername
     *
     * @return the value of toplist.playername
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public String getPlayername() {
        return playername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toplist.playername
     *
     * @param playername the value for toplist.playername
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public void setPlayername(String playername) {
        this.playername = playername == null ? null : playername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toplist.money
     *
     * @return the value of toplist.money
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toplist.money
     *
     * @param money the value for toplist.money
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toplist.score
     *
     * @return the value of toplist.score
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toplist.score
     *
     * @param score the value for toplist.score
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toplist.zan
     *
     * @return the value of toplist.zan
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public Integer getZan() {
        return zan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toplist.zan
     *
     * @param zan the value for toplist.zan
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public void setZan(Integer zan) {
        this.zan = zan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toplist.createtime
     *
     * @return the value of toplist.createtime
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toplist.createtime
     *
     * @param createtime the value for toplist.createtime
     *
     * @mbggenerated Fri Dec 26 17:03:31 CST 2014
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}